### ISSUE TITLE
Replace JSON-based guild configuration system with SQLite/MySQL

### ISSUE THREAD

**Issue by A1Asriel** [A1Asriel/anastellos#10]
Using JSONs as the database is considered bad, unreliable and slow, so Anastellos Engine should use an actual database engine instead.
Ideally, the new solution should be backwards compatible with the current one, so the existing modules would not have to be modified and would continue working as is, without any issues.
Any help will be appreciated.

**Comment by SigmaTel71** [comment]
Assign me this mess.

**Comment by A1Asriel** [comment]
Closed as stale.
